### ISSUE TITLE
Hantering av Parserns syntaxfel

### ISSUE THREAD

**Issue by Jarlius** [Jarlius/Progp-S2#11]
Just nu händer ingenting när det blir syntaxfel i Parsern. Jag ska försöka undersöka hur man kan få syntaxfel att stänga av programmet innan utskrift.

**Comment by simhel2** [comment]
Vi måste få den att skriva "Syntaxfel på rad X" också jag kikar på det.

**Comment by simhel2** [comment]
åh nvm fanns redan

**Comment by Jarlius** [comment]
Jo men bara för Analyser, inte för Parser :disappointed:

**Comment by Jarlius** [comment]
Nu blir detta det sista vi har kvar, förhoppningsvis

**Comment by simhel2** [comment]
så detta är enda felet kvar? vad vi vet iaf
vad sa kattis?

**Comment by Jarlius** [comment]
Kattis säger:

> Syntaxfelsmeddelande skrevs inte ut trots att Leonardo-programmet innehöll syntaxfel.

På test 4, vilket inte är så konstigt eftersom det är en oavslutad loop. Men det är ett syntaxmeddelande som ska komma ifrån Parser, och det har vi inte gjort än.

**Comment by simhel2** [comment]
ok!

**Comment by Jarlius** [comment]
Har kommenterat `TODO: här kan det bli syntaxfel` där Parser ska säga till att det är fel i syntax. Men har inte listat ut hur den ska berätta det för mainfunktionen än... och hur korrekt radsiffra ska skrivas

**Comment by simhel2** [comment]
parsern märker väl att det är error men kan inte rapportera det?
Borde vi inte kunna ha någon kanal som väntar på ett sådant meddellande och ha en counter som räknar rad genom programmet och sen skickas genom kanalen oxå skrivs det ut ett felmeddellande?

**Comment by Jarlius** [comment]
Joo, men mainfunktionen kommer sitta och vänta på att waitgroups ska bli klara, frågan är om den inte kommer att fastna där om Parsern inte uppdaterar sina väntgrupper. Och hur vet Parsern vilken rad den är på?

**Comment by simhel2** [comment]
man kan skicka med från analyser vilken rad man är på kanske ? får kanske ha en kanal som vet det alltid. 
kan man inte låta den här vara utanför waitgroupen eller fungerar det inte så?

**Comment by Jarlius** [comment]
Det är bara mainfunktionen som kan stänga av programmet. Så även om någon tråd utanför maintråden vet om att det är error så stängs det ändå inte av. Kanske går det att stänga av en waitgroup innan den blivit färdig?
Det är nog en bra idé att ha counter för row i Analyser

**Comment by Jarlius** [comment]
Finns bara Add(), Done() och Wait() för waitgroups :cry:

**Comment by Jarlius** [comment]
Hm.. man kanske kan ha en tråd, bara för att vänta på väntgrupperna? Och tråden skickar en boolean True på en kanal som maintråden lyssnar efter. Så om maintråden läser true, skriver den ut värdet från Executor, men om den läser False (skickat från Analyser eller Parser) så skriver den ut error istället?

**Comment by Jarlius** [comment]
Kan visa med exempel

**Comment by simhel2** [comment]
Jag tycker det låter som om det kan fungera

**Comment by simhel2** [comment]
då kan man väl göra om for loopen som lyssnar nu till att lyssna på errors från parser och från analyser samtidigt oxå är ju snyggare

**Comment by Jarlius** [comment]
Den väntar som den ska, men nu blir det panik ibland igen.
Det känns som att det nuvarande inte borde förstöra synkroniseringen, så kanske ändringarna av väntgrupperna förut bara verkade som att dom hjälpte fast inte egentligen?

**Comment by Jarlius** [comment]
Ah, mitt fel, väntrutinen ska ju börja vänta EFTER att scannern har startat..

**Comment by simhel2** [comment]
åh fungerar det nu ? har svårt med all multitrådning tar mig aslång tid :(

**Comment by Jarlius** [comment]
Alltså allting är ju inte löst, men väntrutinen i alla fall

**Comment by simhel2** [comment]
såg att logiklabbredovisningen var 16/12 btw hade sett fel, bara progp labb 6/12, 15/12 är dtek projektgrej.

**Comment by Jarlius** [comment]
Faan, så nära men kommer inte klara :weary:

**Comment by Jarlius** [comment]
Bara citationstecken kvar

**Comment by Jarlius** [comment]
Alltså om dom inte är lika många, måste man kolla i slutet
