### ISSUE TITLE
Wrong answer i Kattis

### ISSUE THREAD

**Issue by Jarlius** [Jarlius/Progp-S2#12]
Jag testkörde precis i Kattis, och eftersom vi inte har rätt felhantering visste jag att det inte skulle fungera. Men jag hittade detta.
Vår utdata på uppgift 2:
```
#FF0000 0.000000 0.000000 1.000000 0.000000
#000000 1.000000 0.000000 2.969616 0.347296
#FF0000 2.969616 0.347296 3.835641 0.847296
#000000 3.835641 0.847296 5.367730 2.132872
#FF0000 5.367730 2.132872 5.867730 2.998897
#000000 5.867730 2.998897 6.551770 4.878282
#111111 6.551770 4.878282 6.551770 5.878282
```
Svaret skulle vara:
```
#FF0000 0.0000 0.0000 1.0000 0.0000
#000000 1.0000 0.0000 2.9696 0.3473
#FF0000 2.9696 0.3473 3.8356 0.8473
#000000 3.8356 0.8473 5.3677 2.1329
#FF0000 5.3677 2.1329 5.8677 2.9989
#000000 5.8677 2.9989 6.5518 4.8783
#111111 6.5518 4.8783 6.5518 3.8783
```
Det blir ett stort fel på den sista.

**Comment by Jarlius** [comment]
Jag har undersökt lite grann och det verkar som att Executor får alla kommandon den behöver. Är det någonting konstigt med sista, BACK 1?

**Comment by simhel2** [comment]
Tittar

**Comment by Jarlius** [comment]
Jaa, det var BACK som var problemet, den ökade istället för att dra ifrån.
Pushar nu

**Comment by simhel2** [comment]
ah oops
