### ISSUE TITLE
Slut på tid, Kattisrester

### ISSUE THREAD

**Issue by Jarlius** [Jarlius/Progp-S2#13]
Vi har nu slut på tid, även om det mesta fungerar, men en hel del kattistester som programmet inte klarade. Adjö bonuspoäng.

Jag tänker ta en paus ett tag nu i alla fall, och fortsätta senare när jag inte skriver en massa spaghetti. Jag kan pusha det jag har just nu så kan du kolla lite om du har lust.

**Comment by simhel2** [comment]
yeah kikar

**Comment by simhel2** [comment]
Tycker vi försöker bli klara idag ändå om det är möjligt

**Comment by Jarlius** [comment]
Jag känner mig helt slutkörd, och vi har inte så mycket de kommande dagarna men du kan gärna fortsätta så länge du orkar.

**Comment by simhel2** [comment]
yeah i will try !

**Comment by simhel2** [comment]
antecknar buggar jag hittar här

**Comment by simhel2** [comment]
1. Sista punkten saknas ger inte error, Ex "FORW 40" fungerar "FORW 40 UP." fungerar inte

**Comment by simhel2** [comment]
2 den accepterar saker som inte har mellanrum mellan ex. "BACK 5.RIGHT 90.UP." fungerar

**Comment by simhel2** [comment]
Det blir panik om det saknas en punkt ex "UP LEFT 1.", "COLOR #123123 RIGHT 1." och 
"REP 1 "RIGHT 1 LEFT 1.""

**Comment by simhel2** [comment]
Det var alla errors som dök upp när man felsökte
testtext som visar felen:

**Comment by simhel2** [comment]
wait wtf tror github har lagt till så att man kan ladda upp saker UTAN konsol commandon får se om jag kan få det att fungera vore ju amazing !

**Comment by Jarlius** [comment]
> **Error information**
> Linje mellan fel par av punkter.
> **Hints about test file**
> Sample input 12.
> Om du har problem med det här fallet, dubbelkolla att din lösning hanterar tabb-tecken.

**Comment by Jarlius** [comment]
Sample 12 blir fel när ett REP utan citationstecken följs av ett nytt REP
