### ISSUE TITLE
Grammatik till Parser

### ISSUE THREAD

**Issue by Jarlius** [Jarlius/Progp-S2#5]
Nu när Analyzer är så gott som klar och skickar fina tokens till Parser börjar det bli dags att planera hur Parser ska se ut.

**Comment by Jarlius** [comment]
Förslag för grammatik:

```
Alfabet:
Kommando (CMD): FORW BACK LEFT RIGHT DOWN UP COLOR REP
Tecken: . (DOT) och " (CIT)
Argument: int (INT) och Color (COL)
```

Först godtas endast kommandon.
`-> CMD`
Efter ett kommando beror det på. Om FORW, BACK, LEFT, RIGHT eller REP, godtas endast Int argument. Efter COLOR godtas endast Color. Efter DOWN och UP godtas endast punkt.
`FORW|BACK|LEFT|RIGHT|REP -> INT`
`COLOR -> COL`
`DOWN|UP -> DOT`
Efter en punkt godtas ett nytt kommando.
`DOT -> CMD`
Färg följs alltid av punkt.
`COL -> DOT`
Är kommandot före heltalsargumentet inte REP godtas punkt.
`INT -> DOT`
När REP godtas skrivs bool repeat till True. Om den är sann godtas kommando eller citation efter heltalsargument.
`INT -> CMD|CIT`
Citationstecken följs utav kommando, om bool repeat fortfarande är True. Varje gång ett kommando som inte är REP godtas sätts repeat till False.  Detta ökar också `cit_count`.
`CIT -> CMD`
Citationstecken kan också följa utav punkt eller ett annat citationstecken, och detta minskar `cit_count`. Blir `cit_count` negativt är det syntaxfel.
`DOT|CIT -> CIT`

För utdata:
Om en punkt godtas kollas om en repetition är i gång. om inte, skicka buffern till Executor.
Om ett citationstecken godtas, kolla om `cit_count` blir noll, i så fall skickas innehållet i buffern.

**Comment by Jarlius** [comment]
Parser gör nu ganska bra ordningskoll av alla tokens förutom REP och CIT. Koden är ganska ful, men logiken är som den ska vara.

**Comment by simhel2** [comment]
kan man skriva en hjälpfunktion för när parser som tar emot allt som är innanför " " för rep och 
1. pausar alla andra trådar
2. kör det innanför reps "" igenom analyser och hela skiten x ggr

känns svårt annars att få allt i rätt ordning och ordningen spelar roll.

**Comment by simhel2** [comment]
Går det att bara pausa feedandet av det första och börja feeda det från rep så skulle det vara bra.
Kankse kan ha multitrådat om vi utökar feeder biten som feedar till analyser?

**Comment by Jarlius** [comment]
Jag tror nog en hjälpmetod är bra, men snarare därför att man kan göra den rekursivt.
Kanske kan Parser endast kolla att allting är i rätt ordning, och låta hjälpfunktionen sköta repetitionerna

**Comment by simhel2** [comment]
Hur kör man koden med exempel?
funderat lite och ville skriva lite men kom på att jag inte vet hur man kör det med de där exemplena

**Comment by Jarlius** [comment]
Som det står i readme testar man med 'cat filnamn | go run s2.go'
Kör du i windows bash? Du kan googla om 'cat filnamn |' är annorlunda i kommandotolk - dvs vad är motsvarigheten för cat, och |

**Comment by simhel2** [comment]
Ty for help! man skrev type istället på windows men fungerade i övrigt

**Comment by Jarlius** [comment]
Så gott som fungerande Parser gör att vi inte behöver denna längre, Case Closed :male_detective:
