### ISSUE TITLE
Executor Aritmetik

### ISSUE THREAD

**Issue by Jarlius** [Jarlius/Progp-S2#7]
Efter att Analyzer och Parser har försäkrat sig om att koden är syntaktiskt och semantiskt korrekt skickas kommandon till Executor, för att beräkna linjerna som sköldpaddan :turtle: Leona ritar när hon vandrar på pappret.

Linjer ska dras från position x1,y1 till x2,y2 i en viss färg, och om pennan är uppe så ska ingen linje dras alls utan om Leona rör sig ska det bara ändra hennes position.

**Comment by Jarlius** [comment]
Skulle starkt rekommendera att du skriver på denna, eftersom den är skild från resten och kan jobbas på parallellt med Parser @simhel2

**Comment by simhel2** [comment]
skriver på den yes

**Comment by simhel2** [comment]
Tror du att svaret ska ges ut i en string?

**Comment by simhel2** [comment]
och den ska inte hantera reps kom vi fram till va?

**Comment by Jarlius** [comment]
Nej inga reps,
Den ska returnera det totala svaret på en kanal, därför att den inte kan printa ut hela tiden - om det blir syntaxfel nån annanstans så får ingenting ha skrivits ut innan

**Comment by simhel2** [comment]
gjort en jätteghetto version nu som svarar som strings.
Måste fixa lite kode dupe och matte bara.
blir ganska många konversioner från string till double/int och tvärtom dock vilket är lite tråkigt

**Comment by simhel2** [comment]
Måste stora koordinaterna som floats för att räkna matte med dem och konvertera argsen från string för att kunna räkna på dem 👎  
Sen måste jag konvertera tillbaks allt till string för att skriva ut 👎

**Comment by simhel2** [comment]
https://www.dropbox.com/s/urr49hmdhtxk14t/s2changes.go?dl=0
Det jag ändrat hittills om du vill se, lägger bara till konstanta siffran 2 på x,y alltid på forw och -2 på back (ökar dem båda med det oavsett vad det står och oavsett vinkel) och har ingen error handling annars fungerar den

**Comment by simhel2** [comment]
https://www.dropbox.com/s/ubq5lipnk4zu91d/s2changes2.go?dl=0 
klar version av den (vi kan lägga till error grejer bara om vi vill men den ska fungera)

**Comment by simhel2** [comment]
hmm verkar inte fungera bra med nya versionen

**Comment by simhel2** [comment]
något du ändrat har fått den att skriva ut allt som görs oxå(det gjorde den inte i gamla varianten, vet inte om det är ett problem egentligen)
Allt efter en rep händer inte i min executor.

**Comment by simhel2** [comment]
Det ser oxå ut som om det kommer massa tomma grejer till executor {    []} vet ej vad det är om

**Comment by simhel2** [comment]
Nu för nya versionen så fungerar den utom för reps

**Comment by simhel2** [comment]
oops lite fel matte såg jag på hur långt den rör sig.

**Comment by simhel2** [comment]
fixat https://www.dropbox.com/s/ubq5lipnk4zu91d/s2changes2.go?dl=0

**Comment by Jarlius** [comment]
Nu pushade jag fungerande repetitioner :tada: 
Lite saker kvar att göra, men gränssnittet till Executor lär vara exakt densamma så vill du så kan du försöka merga koden tillsammans

**Comment by simhel2** [comment]
Får panic på vissa testcases men det andra gör rätt
multitrådningen verkar bråka

**Comment by Jarlius** [comment]
Jag vet, väntgrupperna fungerar inte som de ska så att Parser försöker skicka till Executor efter att den stängts

**Comment by simhel2** [comment]
% Det här är en kommentar
% Nu ritar vi en kvadrat
DOWN.
FORW 1. LEFT 90.
COLOR #123123.
FORW 1. LEFT 90.
FORW 1. LEFT 90.
FORW 1. LEFT 90.
BACK 2. RIGHT 90.
BACK 5. RIGHT 90. 
UP.
RIGHT 90.
DOWN.
FORW 10. 

Detta gav panik etc

**Comment by simhel2** [comment]
ah oki
försöker hjälpa till med det för executorn verkar fungera!

**Comment by Jarlius** [comment]
Vill du kan du skicka senaste versionen av Executor så kan jag merga, det blir mindre klippa o klistra

**Comment by simhel2** [comment]
https://www.dropbox.com/s/40ilqjr2kkj5az7/s2executor.go?dl=0 
här är bara den.
OBS i det andra var det bara den, import (importerade 2 grejer)och några hjälpfunktioner, allt det måste vara med men du kanske har fört över det redan

**Comment by simhel2** [comment]
annars kolla i min förra dropbox länk

**Comment by simhel2** [comment]
eftersom du inte har det i koden som du committat tror jag att du ska föra in det i förra länken dvs : https://www.dropbox.com/s/ubq5lipnk4zu91d/s2changes2.go?dl=0
Byt bara ut importen högst upp, sudda gamla executorn och stoppa in resten längst ner
