### ISSUE TITLE
Dålig synkronisering

### ISSUE THREAD

**Issue by Jarlius** [Jarlius/Progp-S2#9]
På grund av alla ändringar fungerar inte den nuvarande väntgruppen särskilt bra, och vissa utskrifter uteblir. När vi är nästan färdiga får vi gå igenom programmet och synkronisera korrekt så att inget lämnas kvar.

**Comment by Jarlius** [comment]
Väntgrupper skulle kunna organiseras såhär:

1: Scannerlyssnaren räknar hur många rader inputten är
2: Parser räknar hur många Command som måste skickas till Executor för varje rad
3: Executor räknar ned för varje Command den exekverar
4: När Executor gjort färdigt alla Commands så räknar Parser ned en inputrad
5: När Parser har räknat ned att alla inputrader är färdiga kan mainfunktionen skriva ut svaret

**Comment by Jarlius** [comment]
Nej, föregående funkar inte. Såhär gör man nog:

1: Scannerlyssnaren räknar hur många rader inputten är
2: Analyser räknar ut hur många tokens som ska köras och räknar ned rader
3: Parser räknar ut hur många Commands som behövs köras och räknar ned tokens
4: Executor kör Commands och räknar ned Commands.
5: Mainmetoden skriver ut när ALLA tre väntgrupperna är klara.

**Comment by Jarlius** [comment]
Detta borde ha löst problemet, dubbelkolla gärna @simhel2

**Comment by simhel2** [comment]
Får ingen panik längre!
